version: "3"
services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      - REDIS_URL=redis://redis/
      - Authorization=
      - SentryDSN=
      - PGHOST=db
      - PGUSER=matsuri_icu
      - PGPASSWORD=
      - PGDATABASE=matsuri_icu
      - recaptcha=
    links:
      - "redis"
      - "db"
  redis:
    image: "redis:alpine"
  db:
    image: "postgres:13-alpine"
    volumes:
      - D:\test_pg:/var/lib/postgresql/data
